# Generated by Django 5.2.15 on 2026-06-17 16:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("organizations", "0002_auditlog_invitation_organizationmembership"),
    ]

    operations = [
        migrations.CreateModel(
            name="Plan",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "code",
                    models.CharField(
                        choices=[
                            ("free", "Free"),
                            ("team", "Team"),
                            ("business", "Business"),
                            ("enterprise", "Enterprise"),
                        ],
                        max_length=32,
                        unique=True,
                    ),
                ),
                ("name", models.CharField(max_length=64)),
                (
                    "price_inr",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                ("seat_limit", models.PositiveIntegerField(blank=True, null=True)),
                (
                    "students_per_generation_limit",
                    models.PositiveIntegerField(blank=True, null=True),
                ),
                (
                    "generations_per_day_limit",
                    models.PositiveIntegerField(blank=True, null=True),
                ),
                (
                    "monthly_scan_limit",
                    models.PositiveIntegerField(blank=True, null=True),
                ),
                (
                    "razorpay_plan_id",
                    models.CharField(blank=True, default="", max_length=128),
                ),
            ],
            options={
                "ordering": ["price_inr", "code"],
            },
        ),
        migrations.CreateModel(
            name="Subscription",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("created", "Created"),
                            ("active", "Active"),
                            ("past_due", "Past Due"),
                            ("canceled", "Canceled"),
                        ],
                        default="created",
                        max_length=16,
                    ),
                ),
                (
                    "razorpay_subscription_id",
                    models.CharField(blank=True, default="", max_length=128),
                ),
                ("current_period_end", models.DateTimeField(blank=True, null=True)),
                ("seats_purchased", models.PositiveIntegerField(default=1)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "organization",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="subscription",
                        to="organizations.organization",
                    ),
                ),
                (
                    "plan",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="subscriptions",
                        to="billing.plan",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
    ]
