# Generated by Django 5.2.15 on 2026-06-17 17:35

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("organizations", "0002_auditlog_invitation_organizationmembership"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name="auditlog",
            index=models.Index(
                fields=["organization", "created_at"], name="auditlog_org_created_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="organizationmembership",
            index=models.Index(
                fields=["organization", "status"], name="orgmembership_org_status_idx"
            ),
        ),
    ]
