# Generated by Django 5.2.15 on 2026-06-18 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("organizations", "0003_auditlog_auditlog_org_created_idx_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="organization",
            name="default_sheet_heading",
            field=models.CharField(blank=True, default="", max_length=255),
        ),
        migrations.AddField(
            model_name="organization",
            name="logo",
            field=models.ImageField(
                blank=True, null=True, upload_to="branding/org_logos/"
            ),
        ),
    ]
