# Generated by Django 5.2.15 on 2026-06-18 08:43

import common.logo_validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("organizations", "0004_branding_fields"),
    ]

    operations = [
        migrations.AlterField(
            model_name="organization",
            name="logo",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to="branding/org_logos/",
                validators=[common.logo_validators.validate_logo_image],
            ),
        ),
    ]
