# Generated by Django 5.2.15 on 2026-06-19 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("organizations", "0006_classaccessgrant"),
    ]

    operations = [
        migrations.AddField(
            model_name="organization",
            name="type",
            field=models.CharField(
                choices=[
                    ("personal", "Personal"),
                    ("school", "School"),
                    ("college", "College"),
                    ("university", "University"),
                    ("coaching", "Coaching"),
                    ("other", "Other"),
                ],
                default="other",
                max_length=20,
            ),
        ),
    ]
