# Generated by Django 5.2.15 on 2026-06-20 03:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("organizations", "0010_seed_supervisor_office_roles"),
    ]

    operations = [
        migrations.AddField(
            model_name="invitation",
            name="rbac_role",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to="organizations.role",
            ),
        ),
    ]
