# Generated by Django 5.2.15 on 2026-06-20 05:52

import common.logo_validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="MarkingScheme",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "marks_per_correct",
                    models.DecimalField(decimal_places=2, default=1, max_digits=6),
                ),
                (
                    "negative_marks_per_wrong",
                    models.DecimalField(decimal_places=2, default=0, max_digits=6),
                ),
                ("partial_marking", models.BooleanField(default=False)),
                ("multiple_correct_allowed", models.BooleanField(default=False)),
                (
                    "multi_mark_policy",
                    models.CharField(
                        choices=[
                            ("review", "Flag for manual review"),
                            ("disqualify", "Disqualify (zero, no penalty)"),
                            ("wrong", "Mark wrong (apply negative)"),
                            ("correct_if_all", "Correct if all correct options marked"),
                        ],
                        default="review",
                        max_length=16,
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="Option",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("label", models.CharField(max_length=4)),
                ("text", models.CharField(blank=True, max_length=500)),
                (
                    "image",
                    models.ImageField(blank=True, null=True, upload_to="options/"),
                ),
                ("is_correct", models.BooleanField(default=False)),
            ],
            options={
                "ordering": ["label", "id"],
            },
        ),
        migrations.CreateModel(
            name="Question",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("order_index", models.PositiveIntegerField(default=0)),
                ("text", models.TextField()),
                (
                    "image",
                    models.ImageField(blank=True, null=True, upload_to="questions/"),
                ),
                ("topic", models.CharField(blank=True, max_length=255)),
                ("difficulty", models.CharField(blank=True, max_length=20)),
            ],
            options={
                "ordering": ["order_index", "id"],
            },
        ),
        migrations.CreateModel(
            name="Section",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("key", models.CharField(max_length=16)),
                ("label", models.CharField(max_length=255)),
                ("order_index", models.PositiveIntegerField(default=0)),
                ("q_start", models.PositiveIntegerField()),
                ("q_end", models.PositiveIntegerField()),
                (
                    "policy",
                    models.CharField(
                        choices=[("all", "All"), ("choose_k", "Choose K")],
                        default="all",
                        max_length=16,
                    ),
                ),
                ("choose_k", models.PositiveIntegerField(blank=True, null=True)),
            ],
            options={
                "ordering": ["order_index", "id"],
            },
        ),
        migrations.CreateModel(
            name="SectionMarkingScheme",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "marks_per_correct",
                    models.DecimalField(decimal_places=4, default=1, max_digits=8),
                ),
                (
                    "negative_marks_per_wrong",
                    models.DecimalField(decimal_places=4, default=0, max_digits=8),
                ),
                (
                    "negative_kind",
                    models.CharField(
                        choices=[("flat", "Flat"), ("fractional", "Fractional")],
                        default="flat",
                        max_length=12,
                    ),
                ),
                ("partial_marking", models.BooleanField(default=False)),
                ("multiple_correct_allowed", models.BooleanField(default=False)),
                (
                    "qualify_pct",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=5, null=True
                    ),
                ),
                (
                    "multi_mark_policy",
                    models.CharField(
                        choices=[
                            ("review", "Flag for manual review"),
                            ("disqualify", "Disqualify (zero, no penalty)"),
                            ("wrong", "Mark wrong (apply negative)"),
                            ("correct_if_all", "Correct if all correct options marked"),
                        ],
                        default="review",
                        max_length=16,
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="Subject",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("order_index", models.PositiveIntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "ordering": ["order_index", "id"],
            },
        ),
        migrations.CreateModel(
            name="Test",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("title", models.CharField(max_length=255)),
                ("subject", models.CharField(blank=True, max_length=255)),
                ("attempt_number", models.PositiveIntegerField(default=1)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Draft"),
                            ("ready", "Ready"),
                            ("closed", "Closed"),
                        ],
                        default="draft",
                        max_length=10,
                    ),
                ),
                (
                    "mode",
                    models.CharField(
                        choices=[
                            ("standard", "Standard"),
                            ("roster_prebubbled", "Roster (Pre-bubbled roll)"),
                            ("competitive", "Competitive (Sections)"),
                        ],
                        default="standard",
                        max_length=32,
                    ),
                ),
                ("template_spec", models.JSONField(blank=True, default=dict)),
                ("default_options", models.PositiveSmallIntegerField(default=4)),
                (
                    "sheet_heading",
                    models.CharField(blank=True, default="", max_length=255),
                ),
                (
                    "logo",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="branding/logos/",
                        validators=[common.logo_validators.validate_logo_image],
                    ),
                ),
                (
                    "logo_position",
                    models.CharField(
                        choices=[
                            ("left", "Left"),
                            ("center", "Center"),
                            ("right", "Right"),
                        ],
                        default="left",
                        max_length=8,
                    ),
                ),
                ("brand_inherit_org", models.BooleanField(default=True)),
            ],
            options={
                "ordering": ["-created_at", "id"],
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="ClassGroup",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=255)),
                ("description", models.TextField(blank=True)),
                ("kind_label", models.CharField(blank=True, default="", max_length=50)),
                ("order", models.PositiveIntegerField(default=0)),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["order", "name", "id"],
                "abstract": False,
            },
        ),
    ]
