# Generated by Django 5.2.15 on 2026-06-17 11:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("assessments", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="classgroup",
            options={"ordering": ["name", "id"]},
        ),
        migrations.AlterModelOptions(
            name="test",
            options={"ordering": ["-created_at", "id"]},
        ),
    ]
