# Generated by Django 5.2.15 on 2026-06-20 05:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("assessments", "0001_initial"),
        ("folders", "0001_initial"),
        ("organizations", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="classgroup",
            name="folder",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="class_groups",
                to="folders.folder",
            ),
        ),
        migrations.AddField(
            model_name="classgroup",
            name="organization",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="+",
                to="organizations.organization",
            ),
        ),
        migrations.AddField(
            model_name="classgroup",
            name="parent",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="children",
                to="assessments.classgroup",
            ),
        ),
        migrations.AddField(
            model_name="classgroup",
            name="user",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="+",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="option",
            name="question",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="options",
                to="assessments.question",
            ),
        ),
        migrations.AddField(
            model_name="question",
            name="section",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="questions",
                to="assessments.section",
            ),
        ),
        migrations.AddField(
            model_name="sectionmarkingscheme",
            name="section",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="marking_scheme",
                to="assessments.section",
            ),
        ),
        migrations.AddField(
            model_name="subject",
            name="class_group",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="subjects",
                to="assessments.classgroup",
            ),
        ),
        migrations.AddField(
            model_name="test",
            name="class_group",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="tests",
                to="assessments.classgroup",
            ),
        ),
        migrations.AddField(
            model_name="test",
            name="created_by",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="+",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="test",
            name="organization",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="+",
                to="organizations.organization",
            ),
        ),
        migrations.AddField(
            model_name="test",
            name="parent_test",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="retests",
                to="assessments.test",
            ),
        ),
        migrations.AddField(
            model_name="test",
            name="user",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="+",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="section",
            name="test",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="sections",
                to="assessments.test",
            ),
        ),
        migrations.AddField(
            model_name="question",
            name="test",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="questions",
                to="assessments.test",
            ),
        ),
        migrations.AddField(
            model_name="markingscheme",
            name="test",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="marking_scheme",
                to="assessments.test",
            ),
        ),
        migrations.AddConstraint(
            model_name="classgroup",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(("user__isnull", False), ("organization__isnull", True)),
                    models.Q(("user__isnull", True), ("organization__isnull", False)),
                    _connector="OR",
                ),
                name="assessments_classgroup_exactly_one_scope",
            ),
        ),
        migrations.AddConstraint(
            model_name="subject",
            constraint=models.UniqueConstraint(
                fields=("class_group", "name"), name="uniq_subject_class_name"
            ),
        ),
        migrations.AddConstraint(
            model_name="test",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(("user__isnull", False), ("organization__isnull", True)),
                    models.Q(("user__isnull", True), ("organization__isnull", False)),
                    _connector="OR",
                ),
                name="assessments_test_exactly_one_scope",
            ),
        ),
        migrations.AddConstraint(
            model_name="section",
            constraint=models.UniqueConstraint(
                fields=("test", "key"), name="uniq_section_test_key"
            ),
        ),
    ]
