# Generated by Django 5.2.15 on 2026-06-18 02:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("assessments", "0002_alter_classgroup_options_alter_test_options"),
    ]

    operations = [
        migrations.AddField(
            model_name="test",
            name="mode",
            field=models.CharField(
                choices=[
                    ("standard", "Standard"),
                    ("roster_prebubbled", "Roster (Pre-bubbled roll)"),
                ],
                default="standard",
                max_length=32,
            ),
        ),
        migrations.AddField(
            model_name="test",
            name="template_spec",
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
