# Generated by Django 5.2.15 on 2026-06-18 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("assessments", "0005_sms_precision"),
    ]

    operations = [
        migrations.AddField(
            model_name="test",
            name="brand_inherit_org",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="test",
            name="logo",
            field=models.ImageField(blank=True, null=True, upload_to="branding/logos/"),
        ),
        migrations.AddField(
            model_name="test",
            name="logo_position",
            field=models.CharField(
                choices=[("left", "Left"), ("center", "Center"), ("right", "Right")],
                default="left",
                max_length=8,
            ),
        ),
        migrations.AddField(
            model_name="test",
            name="sheet_heading",
            field=models.CharField(blank=True, default="", max_length=255),
        ),
    ]
