# Generated by Django 5.2.15 on 2026-06-18 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("assessments", "0007_add_logo_validator"),
    ]

    operations = [
        migrations.AddField(
            model_name="markingscheme",
            name="multi_mark_policy",
            field=models.CharField(
                choices=[
                    ("review", "Flag for manual review"),
                    ("disqualify", "Disqualify (zero, no penalty)"),
                    ("wrong", "Mark wrong (apply negative)"),
                    ("correct_if_all", "Correct if all correct options marked"),
                ],
                default="review",
                max_length=16,
            ),
        ),
        migrations.AddField(
            model_name="sectionmarkingscheme",
            name="multi_mark_policy",
            field=models.CharField(
                choices=[
                    ("review", "Flag for manual review"),
                    ("disqualify", "Disqualify (zero, no penalty)"),
                    ("wrong", "Mark wrong (apply negative)"),
                    ("correct_if_all", "Correct if all correct options marked"),
                ],
                default="review",
                max_length=16,
            ),
        ),
    ]
