# Generated by Django 5.2.15 on 2026-06-18 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("assessments", "0008_markingscheme_multi_mark_policy_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Subject",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("order_index", models.PositiveIntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "ordering": ["order_index", "id"],
            },
        ),
    ]
