# Generated by Django 5.2.15 on 2026-06-18 12:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("assessments", "0009_subject"),
        ("folders", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="classgroup",
            name="folder",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="class_groups",
                to="folders.folder",
            ),
        ),
        migrations.AddField(
            model_name="subject",
            name="class_group",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="subjects",
                to="assessments.classgroup",
            ),
        ),
        migrations.AddConstraint(
            model_name="subject",
            constraint=models.UniqueConstraint(
                fields=("class_group", "name"), name="uniq_subject_class_name"
            ),
        ),
    ]
