# Generated by Django 5.2.15 on 2026-06-19 09:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("assessments", "0010_classgroup_folder_subject_class_group_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="test",
            name="class_group",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="tests",
                to="assessments.classgroup",
            ),
        ),
    ]
