# Generated by Django 5.2.15 on 2026-06-19 12:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("assessments", "0011_alter_test_class_group"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="classgroup",
            options={"ordering": ["order", "name", "id"]},
        ),
        migrations.AddField(
            model_name="classgroup",
            name="kind_label",
            field=models.CharField(blank=True, default="", max_length=50),
        ),
        migrations.AddField(
            model_name="classgroup",
            name="order",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="classgroup",
            name="parent",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="children",
                to="assessments.classgroup",
            ),
        ),
    ]
