# Generated by Django 5.2.15 on 2026-06-20 05:52

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="StudentProfile",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("score", models.FloatField(default=0.0)),
                ("percentile", models.FloatField(default=0.0)),
                ("rank", models.PositiveIntegerField(default=1)),
                ("cohort_size", models.PositiveIntegerField(default=0)),
            ],
            options={
                "ordering": ["rank", "id"],
            },
        ),
        migrations.CreateModel(
            name="TestProfile",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("profile", models.JSONField(default=dict)),
                ("cohort_size", models.PositiveIntegerField(default=0)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("ok", "OK"),
                            ("insufficient_sample", "Insufficient Sample"),
                            ("no_results", "No Results"),
                        ],
                        default="no_results",
                        max_length=32,
                    ),
                ),
                ("generated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["-generated_at"],
            },
        ),
    ]
