# Generated by Django 5.2.15 on 2026-06-18 04:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("assessments", "0003_mode_and_template_spec"),
        ("results", "0003_widen_reason_add_phase1b_choices"),
        ("rosters", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="TestProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("profile", models.JSONField(default=dict)),
                ("cohort_size", models.PositiveIntegerField(default=0)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("ok", "OK"),
                            ("insufficient_sample", "Insufficient Sample"),
                            ("no_results", "No Results"),
                        ],
                        default="no_results",
                        max_length=32,
                    ),
                ),
                ("generated_at", models.DateTimeField(auto_now=True)),
                (
                    "test",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="profile",
                        to="assessments.test",
                    ),
                ),
            ],
            options={
                "ordering": ["-generated_at"],
            },
        ),
        migrations.CreateModel(
            name="StudentProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("score", models.FloatField(default=0.0)),
                ("percentile", models.FloatField(default=0.0)),
                ("rank", models.PositiveIntegerField(default=1)),
                ("cohort_size", models.PositiveIntegerField(default=0)),
                (
                    "result",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="profile",
                        to="results.studentresult",
                    ),
                ),
                (
                    "student",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="student_profiles",
                        to="rosters.student",
                    ),
                ),
                (
                    "test",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="student_profiles",
                        to="assessments.test",
                    ),
                ),
            ],
            options={
                "ordering": ["rank", "id"],
                "indexes": [
                    models.Index(
                        fields=["test", "student"], name="sprofile_test_student_idx"
                    )
                ],
                "unique_together": {("test", "result")},
            },
        ),
    ]
