# Generated by Django 5.2.15 on 2026-06-20 05:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("analytics", "0001_initial"),
        ("assessments", "0001_initial"),
        ("results", "0001_initial"),
        ("rosters", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="studentprofile",
            name="result",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="profile",
                to="results.studentresult",
            ),
        ),
        migrations.AddField(
            model_name="studentprofile",
            name="student",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="student_profiles",
                to="rosters.student",
            ),
        ),
        migrations.AddField(
            model_name="studentprofile",
            name="test",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="student_profiles",
                to="assessments.test",
            ),
        ),
        migrations.AddField(
            model_name="testprofile",
            name="test",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="profile",
                to="assessments.test",
            ),
        ),
        migrations.AddIndex(
            model_name="studentprofile",
            index=models.Index(
                fields=["test", "student"], name="sprofile_test_student_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="studentprofile",
            unique_together={("test", "result")},
        ),
    ]
