# Generated by Django 5.2.15 on 2026-06-20 05:52

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("assessments", "0001_initial"),
        ("organizations", "0001_initial"),
        ("rosters", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="OmrSheet",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("sheet_code", models.CharField(max_length=64, unique=True)),
                ("human_readable_code", models.CharField(max_length=32)),
                ("shuffle_version", models.BigIntegerField(default=0)),
                ("question_order", models.JSONField(default=list)),
                ("option_order", models.JSONField(default=dict)),
                ("answer_key", models.JSONField(default=dict)),
                ("template_descriptor", models.JSONField(default=dict)),
                ("page_count", models.IntegerField(default=1)),
                ("page_map", models.JSONField(default=dict)),
                (
                    "roll_kind",
                    models.CharField(
                        choices=[
                            ("writein", "Write-in"),
                            ("prebubbled", "Pre-bubbled"),
                            ("none", "None"),
                        ],
                        default="writein",
                        max_length=16,
                    ),
                ),
                ("roll_value", models.CharField(blank=True, default="", max_length=32)),
                (
                    "pdf_file",
                    models.FileField(blank=True, null=True, upload_to="omr_sheets/"),
                ),
                (
                    "question_paper_file",
                    models.FileField(blank=True, null=True, upload_to="omr_papers/"),
                ),
                (
                    "assembly_status",
                    models.CharField(
                        choices=[
                            ("partial", "Partial"),
                            ("ready", "Ready"),
                            ("complete", "Complete"),
                        ],
                        default="partial",
                        max_length=16,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "student",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="omr_sheets",
                        to="rosters.student",
                    ),
                ),
                (
                    "test",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="omr_sheets",
                        to="assessments.test",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at", "id"],
            },
        ),
        migrations.CreateModel(
            name="ScanBatch",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("queued", "Queued"),
                            ("processing", "Processing"),
                            ("done", "Done"),
                        ],
                        default="queued",
                        max_length=16,
                    ),
                ),
                ("total", models.IntegerField(default=0)),
                ("processed", models.IntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="scan_batches",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "test",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="scan_batches",
                        to="assessments.test",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at", "id"],
            },
        ),
        migrations.CreateModel(
            name="ScanEvent",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "organization",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="scan_events",
                        to="organizations.organization",
                    ),
                ),
                (
                    "test",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="scan_events",
                        to="assessments.test",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="scan_events",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="ScanJob",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("page_no", models.IntegerField(default=1)),
                (
                    "image_file",
                    models.FileField(blank=True, null=True, upload_to="scans/"),
                ),
                (
                    "warped_file",
                    models.FileField(blank=True, null=True, upload_to="scans_warped/"),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("queued", "Queued"),
                            ("done", "Done"),
                            ("needs_review", "Needs Review"),
                            ("failed", "Failed"),
                        ],
                        default="queued",
                        max_length=16,
                    ),
                ),
                ("confidence", models.FloatField(blank=True, null=True)),
                ("error_reason", models.TextField(blank=True, default="")),
                (
                    "reads",
                    models.JSONField(
                        default=dict,
                        help_text="Stores this page's bubble reads: {q_pos: {marked: [labels], flag: str|null}, roll: str, flags: [str]}",
                    ),
                ),
                (
                    "batch",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="jobs",
                        to="omr.scanbatch",
                    ),
                ),
                (
                    "omr_sheet",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="scan_jobs",
                        to="omr.omrsheet",
                    ),
                ),
            ],
            options={
                "ordering": ["id"],
            },
        ),
        migrations.CreateModel(
            name="GenerationEvent",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "organization",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="generation_events",
                        to="organizations.organization",
                    ),
                ),
                (
                    "test",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="generation_events",
                        to="assessments.test",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="generation_events",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["organization", "created_at"],
                        name="genevent_org_created_idx",
                    ),
                    models.Index(
                        fields=["user", "created_at"], name="genevent_user_created_idx"
                    ),
                ],
            },
        ),
        migrations.AddIndex(
            model_name="omrsheet",
            index=models.Index(fields=["test"], name="omrsheet_test_idx"),
        ),
        migrations.AddIndex(
            model_name="scanevent",
            index=models.Index(
                fields=["organization", "created_at"], name="scanevent_org_created_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="scanevent",
            index=models.Index(
                fields=["user", "created_at"], name="scanevent_user_created_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="scanjob",
            index=models.Index(fields=["batch"], name="scanjob_batch_idx"),
        ),
        migrations.AddIndex(
            model_name="scanjob",
            index=models.Index(fields=["omr_sheet"], name="scanjob_omrsheet_idx"),
        ),
        migrations.AddIndex(
            model_name="scanjob",
            index=models.Index(fields=["status"], name="scanjob_status_idx"),
        ),
    ]
