# Generated by Django 5.2.15 on 2026-06-17 12:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("assessments", "0002_alter_classgroup_options_alter_test_options"),
        ("rosters", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="OmrSheet",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("sheet_code", models.CharField(max_length=64, unique=True)),
                ("human_readable_code", models.CharField(max_length=32)),
                ("shuffle_version", models.IntegerField(default=0)),
                ("question_order", models.JSONField(default=list)),
                ("option_order", models.JSONField(default=dict)),
                ("answer_key", models.JSONField(default=dict)),
                ("template_descriptor", models.JSONField(default=dict)),
                ("page_count", models.IntegerField(default=1)),
                ("page_map", models.JSONField(default=dict)),
                (
                    "pdf_file",
                    models.FileField(blank=True, null=True, upload_to="omr_sheets/"),
                ),
                (
                    "assembly_status",
                    models.CharField(
                        choices=[("partial", "Partial"), ("ready", "Ready")],
                        default="partial",
                        max_length=16,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "student",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="omr_sheets",
                        to="rosters.student",
                    ),
                ),
                (
                    "test",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="omr_sheets",
                        to="assessments.test",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at", "id"],
            },
        ),
    ]
