# Generated by Django 5.2.15 on 2026-06-17 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("omr", "0002_generationevent"),
    ]

    operations = [
        migrations.AlterField(
            model_name="omrsheet",
            name="shuffle_version",
            field=models.BigIntegerField(default=0),
        ),
    ]
