# Generated by Django 5.2.15 on 2026-06-17 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("omr", "0004_scanbatch_scanjob"),
    ]

    operations = [
        migrations.AddField(
            model_name="scanjob",
            name="reads",
            field=models.JSONField(
                default=dict,
                help_text="Stores this page's bubble reads: {q_pos: {marked: [labels], flag: str|null}, roll: str, flags: [str]}",
            ),
        ),
        migrations.AlterField(
            model_name="omrsheet",
            name="assembly_status",
            field=models.CharField(
                choices=[
                    ("partial", "Partial"),
                    ("ready", "Ready"),
                    ("complete", "Complete"),
                ],
                default="partial",
                max_length=16,
            ),
        ),
    ]
