# Generated by Django 5.2.15 on 2026-06-17 17:35

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("assessments", "0002_alter_classgroup_options_alter_test_options"),
        ("omr", "0006_generationevent_organization_scanevent"),
        ("organizations", "0003_auditlog_auditlog_org_created_idx_and_more"),
        ("rosters", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name="generationevent",
            index=models.Index(
                fields=["organization", "created_at"], name="genevent_org_created_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="generationevent",
            index=models.Index(
                fields=["user", "created_at"], name="genevent_user_created_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="omrsheet",
            index=models.Index(fields=["test"], name="omrsheet_test_idx"),
        ),
        migrations.AddIndex(
            model_name="scanevent",
            index=models.Index(
                fields=["organization", "created_at"], name="scanevent_org_created_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="scanevent",
            index=models.Index(
                fields=["user", "created_at"], name="scanevent_user_created_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="scanjob",
            index=models.Index(fields=["batch"], name="scanjob_batch_idx"),
        ),
        migrations.AddIndex(
            model_name="scanjob",
            index=models.Index(fields=["omr_sheet"], name="scanjob_omrsheet_idx"),
        ),
        migrations.AddIndex(
            model_name="scanjob",
            index=models.Index(fields=["status"], name="scanjob_status_idx"),
        ),
    ]
