# Generated by Django 5.2.15 on 2026-06-18 02:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("omr", "0007_generationevent_genevent_org_created_idx_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="omrsheet",
            name="roll_kind",
            field=models.CharField(
                choices=[
                    ("writein", "Write-in"),
                    ("prebubbled", "Pre-bubbled"),
                    ("none", "None"),
                ],
                default="writein",
                max_length=16,
            ),
        ),
        migrations.AddField(
            model_name="omrsheet",
            name="roll_value",
            field=models.CharField(blank=True, default="", max_length=32),
        ),
    ]
