# Generated by Django 5.2.15 on 2026-06-18 08:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("omr", "0008_roll_kind_and_roll_value"),
    ]

    operations = [
        migrations.AddField(
            model_name="omrsheet",
            name="question_paper_file",
            field=models.FileField(blank=True, null=True, upload_to="omr_papers/"),
        ),
    ]
